sudo: false
language: php

php:
- 7.1
- 7.2
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - nightly

stages:
- check
- test
- coverage
- deploy

jobs:
  include:
  - stage: check
    php: 7.2
    script:
    - composer cs-check
  - stage: coverage
    if: branch = master AND type = push
    php: 7.2
    env: TEST_COVERAGE=true
    before_install:
    - phpenv config-rm xdebug.ini
    script:
    - composer test
    after_script:
    - composer sendcoverage
  - stage: deploy
    if: branch = master AND type = push
    script:
    after_script:
    - openssl aes-256-cbc -K $encrypted_944d199e46d0_key -iv $encrypted_944d199e46d0_iv -in deploy-key.enc -out deploy-key -d && chmod 600 deploy-key;
    - ./vendor/bin/phing deploy;

script:
- composer test

before_install:
- if [[ $DEPS == 'latest' ]]; then travis_retry composer update ; fi
- if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable ; fi
- composer self-update

install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
