version: "2"
services:
  webserver:
    image: nginx:1.11
    ports:
      - "8888:80"
    volumes:
      - ".:/var/www/html"
      - "./.docker/nginx:/etc/nginx/conf.d"
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: ./.docker/php.dockerfile
    working_dir: /var/www/html/public
    volumes:
      - ".:/var/www/html"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    links:
      - mysql

  mysql:
    image: mariadb
    volumes:
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=callingallpapers
      - MYSQL_USER=callingallpapers
      - MYSQL_PASSWORD=callingallpapers
